jobs:
  build:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./build/action

name: Verify

on:
  schedule:
    - cron: "50 2/3 * * *"
